class_implementation/template_project_1/app_1/urls.py
from django.conf.urls import url
from app_1 import views

## template_tagging
app_name = 'app_1' ## Look the under the app_1 and find the url that matches

    # 1) domain_name/app_1/relative --> gives the relative view
    # 2) domain_name/app_1/other    --> gives the other view
urlpatterns = [
    url(r'^other/$',   views.other,   name='other'),
    url(r'^relative/$',views.relative,name='relative'),
]

class_implementation/template_project_1/template_project_1/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from app_1 import views

urlpatterns = [
    url(r'^$',       views.index, name='index'),
    url(r'admin/',   admin.site.urls),
    url(r'^app_1/' , include('app_1.urls'))
]

class_implementation/template_project_1/app_1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'Name':'prashanth S',
                    'Age':21,
                    'Area_of_interest':'Machine Learning'}

    return render(request,'app_1/index.html',context_dict)

def other(request):
    return render(request,'app_1/other.html')

def relative(request):
    return render(request,'app_1/relative_urls_templates.html')

    

class_implementation/template_project_1/templates/app_1/base.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <meta charset='utf-8'>
    <title> Home Page </title>

    <!-- CSS only -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous"> -->
    <link rel="stylesheet" type="text/css" href='{% static "css/bootstrap.min.css"%}'>

    <!-- JavaScript Bundle with Popper -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script> -->
    <script src='{% static "js/bootstrap.min.js" %}'></script>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <div class="container">

            <a class="navbar-brand" href="https://www.djangoproject.com/start/overview/">
                <img src='{% static "images/logo.png" %}' width="50" height="50" alt="Prashanth" loading="lazy" class="d-inline-block align-top"> Prashanth
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar" aria-controls="mynavbar" aria-expanded="false" aria-label="Toggle navigation">
      					<span class="navbar-toggler-icon"></span>
    		</button>

            <div class="justify-content-end collapse navbar-collapse" id="mynavbar">
                <ul class="navbar-nav">
                    <li class="navbar-item">
                        <a class="nav-link active" href="{% url 'app_1:other'%}">Others</a>
                    </li>

                    <li class="navbar-item">
                        <a class="nav-link" href="{% url 'index'%}">Index</a>
                    </li>

                    <li class="navbar-item">
                        <a class="nav-link" href="{% url 'admin:index'%}">Django-admin</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
					        		Dropdown box
					        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="https://www.youtube.com/">Youtube</a>
                            <a class="dropdown-item" href="https://en-gb.facebook.com/">Facebook</a>
                            <div class="dropdown-divider"></div>
                            <!-- A small divider line -->
                            <a class="dropdown-item" href="https://github.com/">Github</a>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

    <div class='container'>
        {% block body_block %}
        <!-- Anything outside this will be inherited
        Inside = Each web-page can have their individual content -->
        {% endblock %}
    </div>

</body>

</html>

class_implementation/template_project_1/templates/app_1/index.html
<!DOCTYPE html> {% extends "app_1/base.html"%} {% block body_block %}
<h1> Welcome to Home Page </h1>
<h2> This is index.html</h2>

<br>

<!-- Built-in filters -->
<h5>Hello, this is {{Name|capfirst}} from Chennai</h5>
<p>I am {{Age}} and exploring {{Area_of_interest}} domain</p>

<br>
<p>Next year I am {{Age|add:"1"}} </p>

<!-- Custom filters -->
<br>
<p> I am going to remove 'n' from my name, So my name is {{Name|cut:'n'}}</p>
{% endblock %}

class_implementation/template_project_1/templates/app_1/other.html
<!DOCTYPE html> {% extends "app_1/base.html"%} {% block body_block %}

<h1> Welcome to other Page </h1>
<h2> This is other.html file </h2>
<h3> This is an example of template inheritance </h3>

{% endblock %}

class_implementation/template_project_1/templates/app_1/relative_urls_templates.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Relative URL's Page</title>
</head>

<body>
    <h1> Welcome to Relative URL Templates </h1>
    <a href="{% url 'app_1:other' %}"> Link to Other Page </a> <br><br>
    <a href="{% url 'admin:index' %}"> Link to Admin Page</a> <br><br>
    <a href="{% url 'index' %}"> Link to Index Page</a>
</body>

</html>