week_5/django_passwords/app_1/urls.py
from django.conf.urls import url
from app_1 import views

app_name = 'app_1'

urlpatterns = [
    url(r'^register/$',views.register,name='register')
]

week_5/django_passwords/django_passwords/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from app_1 import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),

    url(r'^app_1/', include('app_1.urls'))
]

week_5/django_passwords/app_1/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)

    ## additional classes
    portfolio_site = models.URLField(blank=True)  ## User may/may not fill
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

week_5/django_passwords/app_1/forms.py
from django import forms
from django.contrib.auth.models import User
from app_1.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username' , 'email' , 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site' , 'profile_pic')

# Take ('username' , 'email' , 'password') fields from the User model and place in the data-base
# Take ('portfolio_site' , 'profile_pic') fields from the UserProfileInfo model and place in the data-base

week_5/django_passwords/app_1/views.py
from django.shortcuts import render

# Create your views here.

week_5/django_passwords/templates/app_1/base.html
<!DOCTYPE html>
<html>

<head>
    <title>
        Base Page
    </title>
    <link rel="stylesheet" type="text/css" href='{% static "css/bootstrap.min.css"%}'>
    <script src='{% static "js/bootstrap.min.js" %}'></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <div class="container">

            <a class="navbar-brand" href="https://www.djangoproject.com/start/overview/">
                <img src='{% static "images/logo.png" %}' width="50" height="50" alt="Prashanth" loading="lazy" class="d-inline-block align-top"> Prashanth
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar" aria-controls="mynavbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>

            <div class="justify-content-end collapse navbar-collapse" id="mynavbar">
                <ul class="navbar-nav">
                    <li class="navbar-item">
                        <a class="nav-link active" href="{% url 'app_1:index'%}">Django</a>
                    </li>

                    <li class="navbar-item">
                        <a class="nav-link" href="{% url 'admin:index'%}">Admin</a>
                    </li>

                    <li class="navbar-item">
                        <a class="nav-link" href="{% url 'app_1:register'%}">Registration</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Dropdown box
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="https://www.youtube.com/">Youtube</a>
                            <a class="dropdown-item" href="https://en-gb.facebook.com/">Facebook</a>
                            <div class="dropdown-divider"></div>
                            <!-- A small divider line -->
                            <a class="dropdown-item" href="https://github.com/">Github</a>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

    <div class='container'>
        {% block body_block %}
        <!-- Anything outside this will be inherited
        Inside = Each web-page can have their individual content -->
        {% endblock %}
    </div>

</body>

</html>

week_5/django_passwords/templates/app_1/index.html
<!DOCTYPE html> {% extends "app_1/base.html"%} {% block body_block %}

<div class='jumbotron'>
    <h1>Django Level Five</h1>
</div>

{% endblock %}

week_5/django_passwords/templates/app_1/login.html
<!DOCTYPE html>
<html>
<title>

    <head>

    </head>
</title>

<body>

</body>

</html>

week_5/django_passwords/templates/app_1/registration.html
<!DOCTYPE html> {% extends "app_1/base.html"%} {% block body_block %}

<div class='jumbotron'>
    {% if registered %}
    <h1> Thank you for registering </h1>
    {% else %}
    <h1>Register here</h1>
    <h3>Fill out the form</h3>

    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %} {{ user_form.as_p }} {{ profile_form.as_p }}
        <input type='submit' name='' value='Register'>
    </form>
    {% endif %}

</div>

{% endblock %}